#!/usr/bin/env bash
#Script Bash displays 10 times "Best School"
counter=0
while [ $counter -lt 10 ]; do
	if [ $counter -eq 8 ] 
	then
		echo -e "Best School\nHi"
	else
    		echo "Best School"
	fi
    	((counter+=1))
done
